DROP TABLE IF EXISTS burgers_db;
CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers
(
	id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	burger_name varchar(255) NOT NULL,
	devoured Boolean DEFAULT FALSE,
	at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
